# Generated by Django 3.0.5 on 2020-04-29 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('idDriver', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('idRestaurant', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('ReceiverName', models.CharField(max_length=64)),
                ('Meals', django_mysql.models.JSONField(default=dict)),
                ('OrderDate', models.DateTimeField()),
                ('Address', models.CharField(max_length=1024)),
                ('DriverId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Drivers')),
                ('idRestaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Restaurant')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='drivers',
            name='idRestaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Restaurant'),
        ),
    ]
